# Generated by Django 6.0.7 on 2026-08-03 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('recruiter_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('official_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('hiring_volume', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterHiringPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('maximum_active_backlogs', models.PositiveIntegerField(default=0)),
                ('expected_hiring_month', models.CharField(max_length=50)),
                ('expected_students', models.PositiveIntegerField(default=1)),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campus_visit_required', models.BooleanField(default=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_branches', models.ManyToManyField(related_name='recruiter_preferences', to='master_data.branch')),
                ('eligible_programs', models.ManyToManyField(related_name='recruiter_preferences', to='master_data.program')),
                ('hiring_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recruiter_preferences', to='master_data.hiringtype')),
                ('target_job_roles', models.ManyToManyField(related_name='recruiter_preferences', to='master_data.targetjobrole')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recruiter_preferences', to='master_data.workmode')),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_preference', to='recruiters.recruiterprofile')),
            ],
        ),
    ]
