# Generated by Django 6.0.7 on 2026-08-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('profile_completion', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPreviousEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('board_or_university', models.CharField(max_length=255)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qualification_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.qualificationtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_educations', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-year_of_passing'],
            },
        ),
        migrations.CreateModel(
            name='StudentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.employmenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_documents/resumes/')),
                ('class10_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/class10/')),
                ('class12_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/class12/')),
                ('degree_marksheet', models.FileField(blank=True, null=True, upload_to='student_documents/degree/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('batch', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('active_backlogs', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_educations', to='master_data.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_educations', to='master_data.program')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_education', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('permanent_address', models.TextField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='students.studentprofile')),
            ],
        ),
    ]
