# Generated by Django 6.0.7 on 2026-08-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('jobs', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_title', models.CharField(max_length=255)),
                ('drive_date', models.DateField()),
                ('drive_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='institutions.institution')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='jobs.job')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='recruiters.recruiterprofile')),
            ],
            options={
                'ordering': ['-drive_date', '-drive_time'],
            },
        ),
    ]
