# Generated by Django 6.0.7 on 2026-08-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('maximum_active_backlogs', models.PositiveIntegerField(default=0)),
                ('expected_hiring_month', models.CharField(max_length=50)),
                ('application_deadline', models.DateField()),
                ('expected_students', models.PositiveIntegerField(default=1)),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campus_visit_required', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_branches', models.ManyToManyField(related_name='jobs', to='master_data.branch')),
                ('eligible_programs', models.ManyToManyField(related_name='jobs', to='master_data.program')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.employmenttype')),
                ('hiring_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.hiringtype')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiters.recruiterprofile')),
                ('target_job_roles', models.ManyToManyField(related_name='jobs', to='master_data.targetjobrole')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.workmode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
