# Generated by Django 6.0.7 on 2026-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
