# Generated by Django 6.0.7 on 2026-08-03 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('official_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_officer_profile', to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_strength', models.PositiveIntegerField()),
                ('eligible_final_year_students', models.PositiveIntegerField()),
                ('placement_cell_email', models.EmailField(max_length=254)),
                ('placement_cell_phone', models.CharField(max_length=20)),
                ('placement_season', models.CharField(max_length=50)),
                ('placement_policy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_details', to='placement_officers.placementofficerprofile')),
            ],
        ),
    ]
